---
- hosts: spines
  become: yes
  roles:
    - common
    - spines
  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: leafs
  become: yes
  roles:
    - common
    - leafs
  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: xenials 
  gather_facts: False 
  become: yes
  tasks: 
    - name: apt-get update 
      raw: apt-get update -qq 
    - name: Install python 2.7 
      raw: apt-get install -qq python2.7
    - name: Link Python 2.7
      raw: sudo ln -s /usr/bin/python2.7 /usr/bin/python
      ignore_errors: yes

- hosts: servers
  become: yes
  roles:
    - servers
    # - common
  handlers:
    - include: handlers/main.yml
      static: yes
