---
# Setuptools is required for ifupdown2
- name: Check if setuptools is installed
  stat: path=/usr/local/lib/python2.7/dist-packages/setuptools-23.0.0-py2.7.egg
  register: setuptools

- name: Download setuptools
  get_url: url=https://bootstrap.pypa.io/ez_setup.py dest=/home/ubuntu/ez_setup.py
  when: not setuptools.stat.exists

- name: Install setuptools
  shell: python ez_setup.py
  when: not setuptools.stat.exists

# Using apt to install the older ifupdown2 is the simplest way to deal with general dependencies
- name: Install old ifupdown2 via apt
  apt: name=ifupdown2 state=present update_cache=yes

- name: Download ifupdown2
  get_url: >
    url=http://repo3.cumulusnetworks.com/repo/pool/cumulus/i/ifupdown2/ifupdown2_1.1-cl3u3_all.deb
    dest=/home/ubuntu/ifupdown2.deb

# Cumulus ifupdown2 hasn't been upstreamed yet. Install it from their repo
- name: Update ifupdown2 with latest cumulus version
  apt: deb=/home/ubuntu/ifupdown2.deb

# Bridge-utils is required for ifupdown2
- name: Install bridge-utils
  apt: name=bridge-utils state=present update_cache=yes

# python-mako is required for ifupdown2
- name: Install python python-mako
  apt: name=python-mako state=present

# Python pip is required for netshow
- name: Install Python Pip
  apt: name=python-pip state=present

# Netshow simplifies network troubleshooting
- name: Install Netshow
  pip: name=netshow-linux-lib

# Iproute is required for quagga
- name: Install iproute
  apt: name=iproute state=present

- name: Download Quagga
  get_url: >
    url=http://repo3.cumulusnetworks.com/repo/pool/cumulus/q/quagga/quagga_0.99.23.1-1+cl3u2_amd64.deb
    dest=/home/ubuntu/quagga.deb

- name: Install Quagga
  apt: deb=/home/ubuntu/quagga.deb

- name: Copy /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking

- name: Copy Quagga Configuration
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf
  notify: reload quagga
