---
- name: Copy Quagga install package
  copy: >
    src=quagga_0.99.23.1-1+cl3u1_trusty_amd64.deb
    dest=/home/vagrant/quagga.deb

- name: Install Quagga
  apt: deb=/home/vagrant/quagga.deb

- name: Copy Quagga docs package
  copy: >
    src=quagga-doc_0.99.23.1-1+cl3u1_trusty_all.deb
    dest=/home/vagrant/quagga-doc.deb

- name: Install Quagga Docs
  apt: deb=/home/vagrant/quagga-doc.deb

- name: Copy Quagga debug package
  copy: >
    src=quagga-dbg_0.99.23.1-1+cl3u1_trusty_amd64.deb
    dest=/home/vagrant/quagga-dbg.deb

- name: Install Quagga Debugs
  apt: deb=/home/vagrant/quagga-dbg.deb

- name: Copy python cl_cmd server package
  copy: >
    src=python-clcmd_3.0-cl3u1_trusty_all.deb
    dest=/home/vagrant/python-clcmd.deb

- name: Install Python cl_cmd
  apt: deb=/home/vagrant/python-clcmd.deb
